---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family in ['RedHat', 'Rocky']

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-Alpine.yml
  when: ansible_os_family == 'Alpine'

- include: setup-Suse.yml
  when: ansible_os_family == 'Suse'

- name: checkout repo
  git: repo=git://git-mirror.internal.efficios.com/git/linux-all.git
       dest=/home/jenkins/gitcache/linux-stable.git
       bare=yes
  become: yes
  become_user: jenkins
