- hosts: node_standalone
  roles:
    - common
    - common-node
    - cross-compilers
    - babeltrace
    - liburcu
    - lttng-ust
    - lttng-tools
    - lttng-modules
    - lttng-analyses
    - libs-i386
