---
vm_defaults:
  memory: 4194304
  vcpu: 2
  pool: default
  disk_capacity: '80G'
  net_bridge: 'br102'
  # Non-default keys
  # cdrom: /path/to/file.iso
  # uuid: xxxx-yyyy
  # name: xyz
isos:
  - url: https://releases.ubuntu.com/jammy/ubuntu-22.04.2-live-server-amd64.iso
    checksum: "sha256:5e38b55d57d94ff029719342357325ed3bda38fa80054f9330dc789cd2d43931"
    dest: /var/lib/libvirt/images/ubuntu-22.04.2-live-server-amd64.iso
