---
- name: Ensure lttng-tools build dependencies are installed.
  zypper: "name={{ lttng_tools_packages }} state=installed update_cache=yes"

- name: Ensure lttng-tools build dependencies are installed (no recommends).
  zypper: "name={{ lttng_tools_packages_no_recommends }} state=installed disable_recommends=yes"
